Add Webpack sourcemap configuration
benwinding/quill-html-edit-button pull request #25
Opened 2020-11-07 01:14 UTC by JuanCrg90

Currently the webpacker release configuration is generating the
sourcemaps in the same min.js file, This is a problem if you try to
deploy the dependency in some systems, we had a problem deploying the
sourcemaps to sentry, so we updated the configuration to optimize the
file generation and generate the sourcemaps in independent files.

                               Asset       Size  Chunks                   Chunk Names
                         demo.min.js   5.27 KiB       0  [emitted]        demo
                     demo.min.js.map     17 KiB       0  [emitted] [dev]  demo
        quill.htmlEditButton.min.css  818 bytes    0, 1  [emitted]        demo, quill.htmlEditButton
    quill.htmlEditButton.min.css.map  105 bytes    0, 1  [emitted] [dev]  demo, quill.htmlEditButton
         quill.htmlEditButton.min.js   4.92 KiB       1  [emitted]        quill.htmlEditButton
     quill.htmlEditButton.min.js.map   16.1 KiB       1  [emitted] [dev]  quill.htmlEditButton

Co-authored-by: Oscar Zatarain <ozatarain@hotmail.com>

2020-11-07 11:49 UTC, benwinding requested changes
Hey @JuanCrg90,
Thanks for the contribution, but it seems there's a problem with the CSS in the modal (see gif below): 
![Peek 2020-11-07 22-15](https://user-images.githubusercontent.com/11782590/98440147-e9de0100-2146-11eb-9199-56eee3c9a0b1.gif)
Please test locally using the following steps:
- `yarn`
- `yarn build`
- `yarn start` _then navigate to the path in the browser as shown below_

Cheers,
Ben

2020-11-07 16:59 UTC, JuanCrg90 commented
Thanks for your response @benwinding I have updated the Webpack config to support the demo. 

![Screen Recording 2020-11-07 at 10 50 06 AM](https://user-images.githubusercontent.com/2718753/98447016-604b1680-20e7-11eb-870e-626b4928c496.gif)



Now when you run `yarn start` This will build the files for development and will start the dev server
![Screen Recording 2020-11-07 at 10 55 03 AM](https://user-images.githubusercontent.com/2718753/98447094-dfd8e580-20e7-11eb-8d13-b2a4557700b1.gif)

And when you run `yarn build` the build will generate the `*.map` files 😀

![Screen Recording 2020-11-07 at 10 58 10 AM](https://user-images.githubusercontent.com/2718753/98447153-321a0680-20e8-11eb-8c74-680ab6e64220.gif)

2020-11-08 22:57 UTC, benwinding commented
Thanks for fixing that @JuanCrg90,
My only issue is the additional css tag. Usually css tags are fine for large frameworks, theme's etc, but this is a tiny plugin to a tiny WYIWYG editor, so it's a bit annoying to have to add js _and_ css tags.
Can we please have the css bundled with the js? While maintaining the relevant source-maps you need of course
Cheers,
Ben

2020-11-09 17:03 UTC, JuanCrg90 commented
@benwinding Currently we are using the module in a rails application and everything is ok in local using inline sourcemaps, but when we sent the application to our production environment we had a problem with sentry, because It is waiting for a sourcemap file and the dependency has the inline sourcemap 😞 

```
Uploading 15 source maps and 15 minified files.
Uploading -- public/assets/maps/jquery-a653b26f6a7524a8297ae9f430ec522948e36bf8b20276badfd8163deca9eebf.js.map
Uploading -- public/assets/maps/jobs-30388196589e1eed9c67ec7df439484137fdba763c06b32966efb5622d3392cc.js.map
Uploading -- public/assets/maps/admin-71baadea04e6c56baf86f01d6a5e2b06557607d0cde7844b18ed12d09548150b.js.map
Uploading -- publicdata:application/json;charset=utf-8;base64,"+btoa(unescape(encodeURIComponent(JSON.stringify(n))))+" */"),a=o.sources.map(function(e){return"/*# sourceURL="+o.sourceRoot+e+" */"});return[i].concat(a).concat([r]).join("\n")}return[i].join("\n")}(t,e);return t[2]?"@media "+t[2]+"{"+n+"}":n}).join("")},t.i=function(e,n){"string"==typeof e&&(e=[[null,e,""]]);for(var i={},o=0;o<this.length;o++){var r=this[o][0];"number"==typeof r&&(i[r]=!0)}for(o=0;o<e.length;o++){var a=e[o];"number"==typeof a[0]&&i[a[0]]||(n&&!a[2]?a[2]=n:n&&(a[2]="("+a[2]+") and ("+n+")"),t.push(a))}},t}},function(e,t,n){function i(e,t){for(var n=0;n<e.length;n++){var i=e[n],o=m[i.id];if(o){o.refs++;for(var r=0;r<o.parts.length;r++)o.parts[r](i.parts[r]);for(;r<i.parts.length;r++)o.parts.push(c(i.parts[r],t))}else{var a=[];for(r=0;r<i.parts.length;r++)a.push(c(i.parts[r],t));m[i.id]={id:i.id,refs:1,parts:a}}}}function o(e,t){for(var n=[],i={},o=0;o<e.length;o++){var r=e[o],a=t.base?r[0]+t.base:r[0],s={css:r[1],media:r[2],sourceMap:r[3]};i[a]?i[a].parts.push(s):n.push(i[a]={id:a,parts:[s]

rake aborted!
Errno::ENAMETOOLONG: File name too long @ rb_sysopen - publicdata:application/json;charset=utf-8;base64,"+btoa(unescape(encodeURIComponent(JSON.stringify(n))))+" */"),a=o.sources.map(function(e){return"/*# sourceURL="+o.sourceRoot+e+" */"});return[i].concat(a).concat([r]).join("\n")}return[i].join("\n")}(t,e);return t[2]?"@media "+t[2]+"{"+n+"}":n}).join("")},
```

what do you think about to generate inline sourcemaps only for development, but keep the css source map for the production build?

2020-11-10 01:36 UTC, benwinding commented
Oh that doesn't seem good. Well I'm not that familiar with what rake is doing there, looks like it's trying to _remap_ all the source maps or something, right?

Here's a small change to your PR, which should fix it.

### Webpack Config Change
- This will bundle the css into the plugin (no css script tag required), but still creates a `sourcemap` for the bundle. 
- In this PR, please try changing the _module_ field in `webpack.config.js` to the following below:

``` js
// webpack.config.js
...
    module: {
      rules: [
        {
          test: /\.css$/,
          use: ["style-loader", "css-loader"],
        },
        {
          test: /\.js$/,
          exclude: /node_modules/,
          use: {
            loader: "babel-loader",
          },
        },
      ],
    },
```
Let me know how it goes for your build,

Cheers,
Ben

2020-11-10 16:29 UTC, JuanCrg90 commented
@benwinding I've tested sending the sourcemap as you recommend and I got the error that I mentioned before, the problem is that sentry is waiting for tags like

```
//# sourceMappingURL=quill.htmlEditButton.min.js.map
```

```
/*# sourceMappingURL=quill.htmlEditButton.min.css.map*/
```

To upload the specified `map` file to their system. instead of all the base64 inline sourcemap
```js
# sourceMappingURL=data:application/json;charset=utf-8;base64,"+btoa(unescape(encodeURIComponent(JSON.stringify(l))))+" */"),i=r.sources.map((function(e){return"/*# sourceURL="+r.sourceRoot+e+" */"}));return[n].concat(i).concat([o]).join("\n")}var l;return[n].join("\n")}(t,e);return t[2]?"@media "+t[2]+"{"+n+"}":n})).join("")},t.i=function(e,n){"string"==typeof e&&(e=[[null,e,""]]);for(var r={},o=0;o<this.length;o++){var i=this[o][0];"number"==typeof i&&(r[i]=!0)}for(o=0;o<e.length;o++){var l=e[o];"number"==typeof l[0]&&r[l[0]]||(n&&!l[2]?l[2]=n:n&&(l[2]="("+l[2]+") and ("+n+")"),t.push(l))}},t}},function(e,t,n){var r,o,i={},l=(r=function(){return window&&document&&document.all&&!window.atob},function(){return void 0===o&&(o=r.apply(this,arguments)),o}),a=function(e){var t={};return function(n){if(void 0===t[n]){var r=e.call(this,n);if(r instanceof window.HTMLIFrameElement)try{r=r.contentDocument.head}catch(e){r=null}t[n]=r}return t[n]}}((function(e){return document.querySelector(e)})),u=null,s=0,c=[],f=n(5);function p(e,t){for(var n=0;n<e.length;n++){var r=e[n],o=i[r.id];if(o){o.refs++;for(var l=0;l<o.parts.length;l++)o.parts[l](r.parts[l]);for(;l<r.parts.length;l++)o.parts.push(y(r.parts[l],t))}else{var a=[];for(l=0;l<r.parts.length;l++)a.push(y(r.parts[l],t));i[r.id]={id:r.id,refs:1,parts:a}}}}function d(e,t){for(var n=[],r={},o=0;o<e.length;o++){var i=e[o],l=t.base?i[0]+t.base:i[0],a={css:i[1],media:i[2],sourceMap:i[3]};r[l]?r[l].parts.push(a):n.push(r[l]={id:l,parts:[a]})}return n}function h(e,t){var n=a(e.insertInto);if(!n)throw new Error("Couldn't find a style target. This probably means that the value for the 'insertInto' parameter is invalid.");var r=c[c.length-1];if("top"===e.insertAt)r?r.nextSibling?n.insertBefore(t,r.nextSibling):n.appendChild(t):n.insertBefore(t,n.firstChild),c.push(t);else if("bottom"===e.insertAt)n.appendChild(t);else{if("object"!=typeof e.insertAt||!e.insertAt.before)throw new Error("[Style Loader]\n\n Invalid value for parameter 'insertAt' ('options.insertAt') found.\n Must be 'top', 'bottom', or Object.\n (https://github.com/webpack-contrib/style-loader#insertat)\n");var o=a(e.insertInto+" "+e.insertAt.before);n.insertBefore(t,o)}}function b(e){if(null===e.parentNode)return!1;e.parentNode.removeChild(e);var t=c.indexOf(e);t>=0&&c.splice(t,1)}function v(e){var t=document.createElement("style");return e.attrs.type="text/css",m(t,e.attrs),h(e,t),t}function m(e,t){Object.keys(t).forEach((function(n){e.setAttribute(n,t[n])}))}function y(e,t){var n,r,o,i;if(t.transform&&e.css){if(!(i=t.transform(e.css)))return function(){};e.css=i}if(t.singleton){var l=s++;n=u||(u=v(t)),r=w.bind(null,n,l,!1),o=w.bind(null,n,l,!0)}else e.sourceMap&&"function"==typeof URL&&"function"==typeof URL.createObjectURL&&"function"==typeof URL.revokeObjectURL&&"function"==typeof Blob&&"function"==typeof btoa?(n=function(e){var t=document.createElement("link");return e.attrs.type="text/css",e.attrs.rel="stylesheet",m(t,e.attrs),h(e,t),t}(t),r=j.bind(null,n,t),o=function(){b(n),n.href&&URL.revokeObjectURL(n.href)}):(n=v(t),r=C.bind(null,n),o=function(){b(n)});return r(e),function(t){if(t){if(t.css===e.css&&t.media===e.media&&t.sourceMap===e.sourceMap)return;r(e=t)}else o()}}e.exports=function(e,t){if("undefined"!=typeof DEBUG&&DEBUG&&"object"!=typeof document)throw new Error("The style-loader cannot be used in a non-browser environment");(t=t||{}).attrs="object"==typeof t.attrs?t.attrs:{},t.singleton||"boolean"==typeof t.singleton||(t.singleton=l()),t.insertInto||(t.insertInto="head"),t.insertAt||(t.insertAt="bottom");var n=d(e,t);return p(n,t),function(e){for(var r=[],o=0;o<n.length;o++){var l=n[o];(a=i[l.id]).refs--,r.push(a)}e&&p(d(e,t),t);for(o=0;o<r.length;o++){var a;if(0===(a=r[o]).refs){for(var u=0;u<a.parts.length;u++)a.parts[u]();delete i[a.id]}}}};var g,x=(g=[],function(e,t){return g[e]=t,g.filter(Boolean).join("\n")});function w(e,t,n,r){var o=n?"":r.css;if(e.styleSheet)e.styleSheet.cssText=x(t,o);else{var i=document.createTextNode(o),l=e.childNodes;l[t]&&e.removeChild(l[t]),l.length?e.insertBefore(i,l[t]):e.appendChild(i)}}function C(e,t){var n=t.css,r=t.media;if(r&&e.setAttribute("media",r),e.styleSheet)e.styleSheet.cssText=n;else{for(;e.firstChild;)e.removeChild(e.firstChild);e.appendChild(document.createTextNode(n))}}function j(e,t,n){var r=n.css,o=n.sourceMap,i=void 0===t.convertToAbsoluteUrls&&o;(t.convertToAbsoluteUrls||i)&&(r=f(r)),o&&(r+="\n/*# sourceMappingURL=data:application/json;base64,"+btoa(unescape(encodeURIComponent(JSON.stringify(o))))+" */");var l=new Blob([r],{type:"text/css"}),a=e.href;e.href=URL.createObjectURL(l),a&&URL.revokeObjectURL(a)}},function(e,t){e.exports=function(e){var t="undefined"!=typeof window&&window.location;if(!t)throw new Error("fixUrls requires window.location");if(!e||"string"!=typeof e)return e;var n=t.protocol+"//"+t.host,r=n+t.pathname.replace(/\/[^\/]*$/,"/");return e.replace(/url\s*\(((?:[^)(]|\((?:[^)(]+|\([^)(]*\))*\))*)\)/gi,(function(e,t){var o,i=t.trim().replace(/^"(.*)"$/,(function(e,t){return t})).replace(/^'(.*)'$/,(function(e,t){return t}));return/^(#|data:|http:\/\/|https:\/\/|file:\/\/\/)/i.test(i)?e:(o=0===i.indexOf("//")?i:0===i.indexOf("/")?n+i:r+i.replace(/^\.\//,""),"url("+JSON.stringify(o)+")")}))}}])}));
```

2020-11-10 22:00 UTC, benwinding commented
@JuanCrg90,
Ahh sorry, also change the _webpack.config.js_ to:
``` js
    devtool: isProd ? "source-map" : "inline-source-map",
``` 
This should output sourcemap _files_, rather than inline sourcemaps.
Let me know how it goes, cheeers

2020-11-12 06:19 UTC, merged

2020-11-12 06:24 UTC, benwinding commented
Just deployed it as version `2.0.5`

2020-11-13 01:39 UTC, JuanCrg90 commented
Thanks @benwinding 😄